"""Idempotent seed for the food knowledge base (ingredients + dishes).

Run via scripts/init_db.py. Built from Indian-kitchen glossaries
(dals/millets by Hindi name, everyday dish families per main ingredient).
SEASONS maps ingredient -> csv of months (1-12) when it's naturally
available in India; anything missing = available all year.
"""

SEASONS = {
    "mango": "3,4,5,6",
    "watermelon": "3,4,5,6,7",
    "apple": "8,9,10,11,12",
    "orange": "11,12,1,2",
    "pomegranate": "9,10,11,12",
    "grapes": "12,1,2,3",
    "guava": "9,10,11,12",
    "sapota": "1,2,3,4",
    "carrot": "10,11,12,1,2",
    "green-peas": "11,12,1,2",
    "radish": "10,11,12,1,2",
    "beetroot": "10,11,12,1",
    "fenugreek-leaves": "11,12,1,2",
    "spinach": "10,11,12,1,2",
    "cucumber": "3,4,5,6",
    "drumstick": "2,3,4,5",
}

FOOD_DATA = {
    # category: [(name, common_names_csv)]
    "vegetable": [
        ("potato", "aloo,batata"),
        ("onion", "pyaaz,pyaaj"),
        ("tomato", "tamatar"),
        ("cauliflower", "gobi,gobhi,phool gobi"),
        ("cabbage", "patta gobi,bandh gobi"),
        ("brinjal", "baingan,eggplant,aubergine"),
        ("okra", "bhindi,lady finger"),
        ("spinach", "palak"),
        ("fenugreek-leaves", "methi"),
        ("bottle-gourd", "lauki,ghiya,ghia,dudhi"),
        ("ridge-gourd", "turai,tori"),
        ("pumpkin", "kaddu"),
        ("capsicum", "shimla mirch,bell pepper"),
        ("green-peas", "matar,mutter,watana"),
        ("carrot", "gajar"),
        ("radish", "mooli,muli"),
        ("cucumber", "kheera"),
        ("beetroot", "chukandar"),
        ("mushroom", "khumb"),
        ("sweet-potato", "shakarkandi"),
        ("bitter-gourd", "karela"),
        ("taro", "arbi"),
        ("raw-banana", "kaccha kela"),
        ("drumstick", "sahjan,sehjan"),
        ("green-chilli", "hari mirch"),
        ("ginger", "adrak"),
        ("garlic", "lehsun"),
        ("coriander-leaves", "dhaniya"),
        ("mint", "pudina"),
    ],
    "fruit": [
        ("apple", "seb"),
        ("banana", "kela"),
        ("mango", "aam"),
        ("papaya", "papita"),
        ("orange", "santra,mosambi"),
        ("pomegranate", "anar"),
        ("watermelon", "tarbooz"),
        ("grapes", "angoor"),
        ("guava", "amrood"),
        ("sapota", "chikoo"),
    ],
    "lentil": [
        ("toor-dal", "arhar dal,tuvar,pigeon pea"),
        ("moong-dal", "moong,mung"),
        ("masoor-dal", "masoor"),
        ("chana-dal", "bengal gram"),
        ("urad-dal", "udad,black gram"),
        ("rajma", "kidney beans"),
        ("chickpeas", "chole,kabuli chana,chhole,garbanzo"),
        ("kala-chana", "black chickpeas"),
        ("lobia", "chawli,black-eyed peas"),
        ("matki", "moth beans"),
    ],
    "grain": [
        ("wheat-atta", "atta,gandum,wheat"),
        ("rice", "chawal"),
        ("besan", "gram flour,chickpea flour"),
        ("ragi", "finger millet,nachni"),
        ("jowar", "sorghum"),
        ("bajra", "pearl millet"),
        ("oats", ""),
        ("poha", "flattened rice,chivda"),
        ("sooji", "rava,semolina"),
        ("sabudana", "sago,tapioca pearls"),
        ("makhana", "fox nuts,lotus seeds"),
        ("daliya", "broken wheat"),
        ("corn", "makai,makka,bhutta,sweet corn"),
    ],
    "sprout": [
        ("moong-sprouts", "ankurit moong,sprouted moong"),
        ("chana-sprouts", "sprouted kala chana"),
        ("matki-sprouts", "sprouted matki"),
    ],
    "dairy": [
        ("dahi", "curd,yogurt,dahi"),
        ("paneer", "cottage cheese"),
        ("milk", "doodh"),
        ("cheese", ""),
    ],
    "protein": [
        ("eggs", "anda"),
        ("soya-chunks", "nutrela,meal maker"),
        ("peanut", "moongphali,groundnut"),
    ],
}

# name -> (meal_types, [ingredient names])
DISHES = {
    # -- breakfast / snacks (staple morning foods)
    "Poha": ("breakfast,snack", ["poha", "potato", "green-peas", "onion"]),
    "Upma": ("breakfast,snack", ["sooji", "green-peas", "tomato"]),
    "Idli sambar": ("breakfast,dinner", ["rice", "urad-dal"]),
    "Masala dosa": ("breakfast,dinner", ["rice", "urad-dal", "potato"]),
    "Aloo paratha": ("breakfast,snack", ["wheat-atta", "potato"]),
    "Gobi paratha": ("breakfast,snack", ["wheat-atta", "cauliflower"]),
    "Mooli paratha": ("breakfast,snack", ["wheat-atta", "radish"]),
    "Paneer paratha": ("breakfast,snack", ["wheat-atta", "paneer"]),
    "Palak paratha": ("breakfast,snack", ["wheat-atta", "spinach"]),
    "Methi paratha": ("breakfast,snack", ["wheat-atta", "fenugreek-leaves"]),
    "Besan chilla": ("breakfast,snack", ["besan", "onion", "tomato"]),
    "Moong dal chilla": ("breakfast,snack", ["moong-dal"]),
    "Egg bhurji": ("breakfast", ["eggs", "onion", "tomato"]),
    "Sabudana khichdi": ("breakfast,snack", ["sabudana", "potato", "peanut"]),
    "Oats porridge": ("breakfast", ["oats", "milk"]),
    "Ragi dosa": ("breakfast", ["ragi", "rice"]),
    "Ragi porridge": ("breakfast", ["ragi", "milk"]),
    "Sprout chaat": ("breakfast,snack", ["moong-sprouts", "onion", "tomato"]),
    "Uttapam": ("breakfast,dinner", ["rice", "urad-dal", "onion", "tomato"]),
    "Veg sandwich": ("snack,breakfast", ["tomato", "cucumber", "beetroot", "cheese"]),

    # -- lunch / dinner mains
    "Dal tadka": ("lunch,dinner", ["toor-dal", "tomato"]),
    "Dal fry": ("lunch,dinner", ["toor-dal", "masoor-dal", "tomato"]),
    "Dal makhani": ("lunch,dinner", ["urad-dal"]),
    "Moong dal khichdi": ("dinner,lunch", ["moong-dal", "rice"]),
    "Chana dal fry": ("lunch,dinner", ["chana-dal"]),
    "Lauki chana dal": ("lunch,dinner", ["bottle-gourd", "chana-dal"]),
    "Jeera rice": ("lunch,dinner", ["rice"]),
    "Veg pulao": ("lunch,dinner", ["rice", "green-peas", "carrot", "capsicum"]),
    "Veg biryani": ("lunch,dinner", ["rice", "potato", "cauliflower", "carrot", "green-peas"]),
    "Curd rice": ("lunch,dinner", ["rice", "dahi"]),
    "Rajma chawal": ("lunch,dinner", ["rajma", "rice"]),
    "Chole chawal": ("lunch,dinner", ["chickpeas", "rice"]),
    "Chole bhature": ("lunch", ["chickpeas", "wheat-atta"]),
    "Kala chana masala": ("lunch,dinner", ["kala-chana", "onion"]),
    "Aloo gobi": ("lunch,dinner", ["potato", "cauliflower"]),
    "Aloo matar": ("lunch,dinner", ["potato", "green-peas"]),
    "Aloo methi": ("lunch,dinner", ["potato", "fenugreek-leaves"]),
    "Aloo palak": ("lunch,dinner", ["potato", "spinach"]),
    "Jeera aloo": ("lunch,dinner,breakfast", ["potato"]),
    "Dum aloo": ("lunch,dinner", ["potato", "dahi"]),
    "Aloo bhindi": ("lunch,dinner", ["potato", "okra"]),
    "Bhindi masala": ("lunch,dinner", ["okra", "onion"]),
    "Baingan bharta": ("lunch,dinner", ["brinjal", "tomato", "onion"]),
    "Aloo baingan": ("lunch,dinner", ["potato", "brinjal"]),
    "Palak paneer": ("lunch,dinner", ["spinach", "paneer"]),
    "Matar paneer": ("lunch,dinner", ["paneer", "green-peas"]),
    "Kadhai paneer": ("lunch,dinner", ["paneer", "capsicum", "onion"]),
    "Shahi paneer": ("lunch,dinner", ["paneer", "tomato"]),
    "Paneer bhurji": ("lunch,dinner,breakfast", ["paneer", "onion", "tomato"]),
    "Paneer tikka": ("snack,dinner", ["paneer", "capsicum", "onion"]),
    "Cabbage sabzi": ("lunch,dinner", ["cabbage", "green-peas"]),
    "Gajar matar": ("lunch,dinner", ["carrot", "green-peas"]),
    "Pumpkin sabzi": ("lunch,dinner", ["pumpkin"]),
    "Lauki sabzi": ("lunch,dinner", ["bottle-gourd"]),
    "Turai sabzi": ("lunch,dinner", ["ridge-gourd"]),
    "Mixed veg sabzi": ("lunch,dinner", ["capsicum", "carrot", "green-peas", "cauliflower"]),
    "Mushroom matar": ("lunch,dinner", ["mushroom", "green-peas"]),
    "Soya chunk curry": ("lunch,dinner", ["soya-chunks", "onion"]),
    "Egg curry": ("lunch,dinner", ["eggs", "onion", "tomato"]),
    "Kadhi pakora": ("lunch,dinner", ["besan", "dahi"]),
    "Gobi manchurian": ("dinner,snack", ["cauliflower"]),
    "Pav bhaji": ("dinner,snack", ["potato", "tomato", "capsicum", "green-peas"]),
    "Bajra roti": ("lunch,dinner", ["bajra"]),
    "Jowar bhakri": ("lunch,dinner", ["jowar"]),
    "Ragi roti": ("lunch", ["ragi"]),
    "Daliya khichdi": ("dinner", ["daliya", "green-peas"]),
    "Tomato soup": ("dinner", ["tomato", "carrot"]),
    "Palak soup": ("dinner", ["spinach"]),
    "Karela fry": ("lunch,dinner", ["bitter-gourd"]),

    # -- snacks / drinks / sweets
    "Samosa": ("snack", ["wheat-atta", "potato", "green-peas"]),
    "Pakora (bhajiya)": ("snack", ["besan", "onion", "potato"]),
    "Aloo tikki": ("snack", ["potato", "green-peas"]),
    "Fruit chaat": ("snack,breakfast", ["apple", "banana", "pomegranate", "papaya"]),
    "Banana shake": ("snack,breakfast", ["banana", "milk"]),
    "Mango shake": ("snack", ["mango", "milk"]),
    "Lassi": ("snack", ["dahi"]),
    "Roasted makhana": ("snack", ["makhana"]),
    "Roasted peanuts": ("snack", ["peanut"]),
    "Dhokla": ("snack,breakfast", ["besan"]),
    "Masala corn": ("snack", ["makka"]),
    "Popcorn": ("snack", ["makka"]),
    "Hara bhara kabab": ("snack", ["spinach", "green-peas", "potato"]),
    "Chana chaat": ("snack", ["kala-chana", "onion"]),
    "Moong sprout salad": ("snack", ["moong-sprouts", "onion"]),
    "Kheer": ("snack", ["rice", "milk"]),
    "Gajar halwa": ("snack", ["carrot", "milk"]),
}

